// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Footer → Menu Footer*
 */
export interface FooterDocumentDataFooterItem {
  /**
   * Nom menu field in *Footer → Menu Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer[].nom_menu
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nom_menu: prismic.KeyTextField;

  /**
   * Lien vers la page page du menu field in *Footer → Menu Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer[].lien_vers_la_page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien_vers_la_page: prismic.LinkField;
}

/**
 * Item in *Footer → Politiques de confidentialité*
 */
export interface FooterDocumentDataPolitiquesDeConfidentialiteItem {
  /**
   * Titre de le politique field in *Footer → Politiques de confidentialité*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.politiques_de_confidentialite[].politique_de_confidentialite
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  politique_de_confidentialite: prismic.KeyTextField;

  /**
   * Lien vers la politique field in *Footer → Politiques de confidentialité*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.politiques_de_confidentialite[].lien_vers_la_politique
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien_vers_la_politique: prismic.LinkField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Menu Footer field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer: prismic.GroupField<Simplify<FooterDocumentDataFooterItem>>;

  /**
   * Politiques de confidentialité field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.politiques_de_confidentialite[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  politiques_de_confidentialite: prismic.GroupField<
    Simplify<FooterDocumentDataPolitiquesDeConfidentialiteItem>
  >;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Menu → Menu de navigation*
 */
export interface MenuDocumentDataMenuDeNavigationItem {
  /**
   * Label du menu field in *Menu → Menu de navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_de_navigation[].label_du_menu
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_du_menu: prismic.KeyTextField;

  /**
   * Lien du menu field in *Menu → Menu de navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_de_navigation[].lien_du_menu
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien_du_menu: prismic.LinkField;
}

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
  /**
   * Titre du site field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.titre_du_site
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_du_site: prismic.KeyTextField;

  /**
   * Description field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Image par défaut field in *Menu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.image_par_defaut
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_par_defaut: prismic.ImageField<never>;

  /**
   * Menu de navigation field in *Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_de_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_de_navigation: prismic.GroupField<
    Simplify<MenuDocumentDataMenuDeNavigationItem>
  >;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

type PageDocumentDataSlicesSlice =
  | PageContactSlice
  | CatchPhraseSectionSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = FooterDocument | MenuDocument | PageDocument;

/**
 * Item in *CatchPhraseSection → Default → Primary → Button à propos*
 */
export interface CatchPhraseSectionSliceDefaultPrimaryButtonAProposItem {
  /**
   * Label  field in *CatchPhraseSection → Default → Primary → Button à propos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.button_a_propos[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Lien field in *CatchPhraseSection → Default → Primary → Button à propos*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.button_a_propos[].lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien: prismic.LinkField;
}

/**
 * Item in *CatchPhraseSection → Default → Primary → Section photo personnes ayant testé*
 */
export interface CatchPhraseSectionSliceDefaultPrimarySectionPhotoPersonnesAyantTesteItem {
  /**
   * Photo field in *CatchPhraseSection → Default → Primary → Section photo personnes ayant testé*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.section_photo_personnes_ayant_teste[].photo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo: prismic.ImageField<never>;

  /**
   * numbre de personnes ayant aimées field in *CatchPhraseSection → Default → Primary → Section photo personnes ayant testé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.section_photo_personnes_ayant_teste[].numbre_de_personnes_ayant_aimees
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  numbre_de_personnes_ayant_aimees: prismic.KeyTextField;
}

/**
 * Primary content in *CatchPhraseSection → Default → Primary*
 */
export interface CatchPhraseSectionSliceDefaultPrimary {
  /**
   * Titre field in *CatchPhraseSection → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre: prismic.TitleField;

  /**
   * Sous-titre field in *CatchPhraseSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.sous_titre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sous_titre: prismic.RichTextField;

  /**
   * photo mobile field in *CatchPhraseSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.photo_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo_mobile: prismic.ImageField<never>;

  /**
   * Button à propos field in *CatchPhraseSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.button_a_propos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  button_a_propos: prismic.GroupField<
    Simplify<CatchPhraseSectionSliceDefaultPrimaryButtonAProposItem>
  >;

  /**
   * Section photo personnes ayant testé field in *CatchPhraseSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.section_photo_personnes_ayant_teste[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  section_photo_personnes_ayant_teste: prismic.GroupField<
    Simplify<CatchPhraseSectionSliceDefaultPrimarySectionPhotoPersonnesAyantTesteItem>
  >;

  /**
   * Phrase des personnes qui ont testé field in *CatchPhraseSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.phrase_des_personnes_qui_ont_testes
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phrase_des_personnes_qui_ont_testes: prismic.RichTextField;
}

/**
 * Default variation for CatchPhraseSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CatchPhraseSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CatchPhraseSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CatchPhraseSection*
 */
type CatchPhraseSectionSliceVariation = CatchPhraseSectionSliceDefault;

/**
 * CatchPhraseSection Shared Slice
 *
 * - **API ID**: `catch_phrase_section`
 * - **Description**: CatchPhraseSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CatchPhraseSectionSlice = prismic.SharedSlice<
  "catch_phrase_section",
  CatchPhraseSectionSliceVariation
>;

/**
 * Primary content in *PageContact → Default → Primary*
 */
export interface PageContactSliceDefaultPrimary {
  /**
   * Titre page de contact field in *PageContact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.default.primary.titre_page_contact
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre_page_contact: prismic.RichTextField;

  /**
   * Pseudo utilisateur field in *PageContact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.default.primary.pseudo_utilisateur
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pseudo_utilisateur: prismic.KeyTextField;

  /**
   * Adresse mail field in *PageContact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.default.primary.adresse_mail
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  adresse_mail: prismic.KeyTextField;

  /**
   * champ de message field in *PageContact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.default.primary.champ_de_message
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  champ_de_message: prismic.KeyTextField;

  /**
   * Image icon message field in *PageContact → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.default.primary.image_icon_message
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_icon_message: prismic.ImageField<never>;

  /**
   * button envoyer field in *PageContact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.default.primary.button_envoyer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_envoyer: prismic.KeyTextField;
}

/**
 * Default variation for PageContact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PageContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PageContact*
 */
type PageContactSliceVariation = PageContactSliceDefault;

/**
 * PageContact Shared Slice
 *
 * - **API ID**: `page_contact`
 * - **Description**: PageContact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageContactSlice = prismic.SharedSlice<
  "page_contact",
  PageContactSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataFooterItem,
      FooterDocumentDataPolitiquesDeConfidentialiteItem,
      MenuDocument,
      MenuDocumentData,
      MenuDocumentDataMenuDeNavigationItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CatchPhraseSectionSlice,
      CatchPhraseSectionSliceDefaultPrimaryButtonAProposItem,
      CatchPhraseSectionSliceDefaultPrimarySectionPhotoPersonnesAyantTesteItem,
      CatchPhraseSectionSliceDefaultPrimary,
      CatchPhraseSectionSliceVariation,
      CatchPhraseSectionSliceDefault,
      PageContactSlice,
      PageContactSliceDefaultPrimary,
      PageContactSliceVariation,
      PageContactSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
