// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Footer → Menu Footer*
 */
export interface FooterDocumentDataFooterItem {
  /**
   * Nom menu field in *Footer → Menu Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer[].nom_menu
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nom_menu: prismic.KeyTextField;

  /**
   * Lien vers la page page du menu field in *Footer → Menu Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer[].lien_vers_la_page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien_vers_la_page: prismic.LinkField;
}

/**
 * Item in *Footer → Politiques de confidentialité*
 */
export interface FooterDocumentDataPolitiquesDeConfidentialiteItem {
  /**
   * Titre de le politique field in *Footer → Politiques de confidentialité*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.politiques_de_confidentialite[].politique_de_confidentialite
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  politique_de_confidentialite: prismic.KeyTextField;

  /**
   * Lien vers la politique field in *Footer → Politiques de confidentialité*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.politiques_de_confidentialite[].lien_vers_la_politique
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien_vers_la_politique: prismic.LinkField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Menu Footer field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer: prismic.GroupField<Simplify<FooterDocumentDataFooterItem>>;

  /**
   * Politiques de confidentialité field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.politiques_de_confidentialite[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  politiques_de_confidentialite: prismic.GroupField<
    Simplify<FooterDocumentDataPolitiquesDeConfidentialiteItem>
  >;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Menu → Menu de navigation*
 */
export interface MenuDocumentDataMenuDeNavigationItem {
  /**
   * Label du menu field in *Menu → Menu de navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_de_navigation[].label_du_menu
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_du_menu: prismic.KeyTextField;

  /**
   * Lien du menu field in *Menu → Menu de navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_de_navigation[].lien_du_menu
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien_du_menu: prismic.LinkField;
}

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
  /**
   * Titre du site field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.titre_du_site
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_du_site: prismic.KeyTextField;

  /**
   * Description field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Image par défaut field in *Menu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.image_par_defaut
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_par_defaut: prismic.ImageField<never>;

  /**
   * Menu de navigation field in *Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_de_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_de_navigation: prismic.GroupField<
    Simplify<MenuDocumentDataMenuDeNavigationItem>
  >;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

type PageDocumentDataSlicesSlice =
  | CatalogueThirdSliceSlice
  | CatalogueSecondSliceSlice
  | CatalogueFirstSliceSlice
  | SecondSliceFormationSlice
  | FirstSliceFormationSlice
  | PageAProposSlice
  | ParcoursTimeoSlice
  | TransformationSlice
  | DeveloppementSlice
  | EveilIndividuelSlice
  | PageContactSlice
  | CatchPhraseSectionSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = FooterDocument | MenuDocument | PageDocument;

/**
 * Item in *CatalogueFirstSlice → Default → Primary → Les offres Timéo*
 */
export interface CatalogueFirstSliceSliceDefaultPrimaryLesOffresTimeoItem {
  /**
   * Titre field in *CatalogueFirstSlice → Default → Primary → Les offres Timéo*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_first_slice.default.primary.les_offres_timeo[].titre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre: prismic.RichTextField;

  /**
   * Description field in *CatalogueFirstSlice → Default → Primary → Les offres Timéo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_first_slice.default.primary.les_offres_timeo[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *CatalogueFirstSlice → Default → Primary → Button nous contacter*
 */
export interface CatalogueFirstSliceSliceDefaultPrimaryButtonNousContacterItem {
  /**
   * Placeholder field in *CatalogueFirstSlice → Default → Primary → Button nous contacter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_first_slice.default.primary.button_nous_contacter[].placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  placeholder: prismic.KeyTextField;

  /**
   * Lien vers la page field in *CatalogueFirstSlice → Default → Primary → Button nous contacter*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_first_slice.default.primary.button_nous_contacter[].lien_vers_la_page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien_vers_la_page: prismic.LinkField;
}

/**
 * Primary content in *CatalogueFirstSlice → Default → Primary*
 */
export interface CatalogueFirstSliceSliceDefaultPrimary {
  /**
   * Image de fond de page field in *CatalogueFirstSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_first_slice.default.primary.image_de_fond_de_page
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_de_fond_de_page: prismic.ImageField<never>;

  /**
   * Titre field in *CatalogueFirstSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_first_slice.default.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre: prismic.RichTextField;

  /**
   * Description field in *CatalogueFirstSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_first_slice.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Les offres Timéo field in *CatalogueFirstSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_first_slice.default.primary.les_offres_timeo[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  les_offres_timeo: prismic.GroupField<
    Simplify<CatalogueFirstSliceSliceDefaultPrimaryLesOffresTimeoItem>
  >;

  /**
   * Button nous contacter field in *CatalogueFirstSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_first_slice.default.primary.button_nous_contacter[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  button_nous_contacter: prismic.GroupField<
    Simplify<CatalogueFirstSliceSliceDefaultPrimaryButtonNousContacterItem>
  >;
}

/**
 * Default variation for CatalogueFirstSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CatalogueFirstSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CatalogueFirstSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CatalogueFirstSlice*
 */
type CatalogueFirstSliceSliceVariation = CatalogueFirstSliceSliceDefault;

/**
 * CatalogueFirstSlice Shared Slice
 *
 * - **API ID**: `catalogue_first_slice`
 * - **Description**: CatalogueFirstSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CatalogueFirstSliceSlice = prismic.SharedSlice<
  "catalogue_first_slice",
  CatalogueFirstSliceSliceVariation
>;

/**
 * Item in *CatalogueSecondSlice → Default → Primary → Detail de contenus de coffret*
 */
export interface CatalogueSecondSliceSliceDefaultPrimaryDetailDeContenusDeCoffretItem {
  /**
   * Détail field in *CatalogueSecondSlice → Default → Primary → Detail de contenus de coffret*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_second_slice.default.primary.detail_de_contenus_de_coffret[].detail
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  detail: prismic.KeyTextField;
}

/**
 * Item in *CatalogueSecondSlice → Default → Primary → Button demander un devis*
 */
export interface CatalogueSecondSliceSliceDefaultPrimaryButtonDemanderUnDevisItem {
  /**
   * Placeholder field in *CatalogueSecondSlice → Default → Primary → Button demander un devis*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_second_slice.default.primary.button_demander_un_devis[].placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  placeholder: prismic.KeyTextField;

  /**
   * Lien vers la page field in *CatalogueSecondSlice → Default → Primary → Button demander un devis*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_second_slice.default.primary.button_demander_un_devis[].lien_vers_la_page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien_vers_la_page: prismic.LinkField;
}

/**
 * Primary content in *CatalogueSecondSlice → Default → Primary*
 */
export interface CatalogueSecondSliceSliceDefaultPrimary {
  /**
   * Titre field in *CatalogueSecondSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_second_slice.default.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre: prismic.RichTextField;

  /**
   * Titre Prix par coffret field in *CatalogueSecondSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_second_slice.default.primary.titre_prix_par_coffret
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre_prix_par_coffret: prismic.RichTextField;

  /**
   * Detail de contenus de coffret field in *CatalogueSecondSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_second_slice.default.primary.detail_de_contenus_de_coffret[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  detail_de_contenus_de_coffret: prismic.GroupField<
    Simplify<CatalogueSecondSliceSliceDefaultPrimaryDetailDeContenusDeCoffretItem>
  >;

  /**
   * Button demander un devis field in *CatalogueSecondSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_second_slice.default.primary.button_demander_un_devis[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  button_demander_un_devis: prismic.GroupField<
    Simplify<CatalogueSecondSliceSliceDefaultPrimaryButtonDemanderUnDevisItem>
  >;
}

/**
 * Default variation for CatalogueSecondSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CatalogueSecondSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CatalogueSecondSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CatalogueSecondSlice*
 */
type CatalogueSecondSliceSliceVariation = CatalogueSecondSliceSliceDefault;

/**
 * CatalogueSecondSlice Shared Slice
 *
 * - **API ID**: `catalogue_second_slice`
 * - **Description**: CatalogueSecondSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CatalogueSecondSliceSlice = prismic.SharedSlice<
  "catalogue_second_slice",
  CatalogueSecondSliceSliceVariation
>;

/**
 * Item in *CatalogueThirdSlice → Default → Primary → Catalogue saison 1*
 */
export interface CatalogueThirdSliceSliceDefaultPrimaryCatalogueSaison1Item {
  /**
   * Image catalogue field in *CatalogueThirdSlice → Default → Primary → Catalogue saison 1*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_third_slice.default.primary.catalogue_saison_1[].image_catalogue
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_catalogue: prismic.ImageField<never>;

  /**
   * Valeur traîtée field in *CatalogueThirdSlice → Default → Primary → Catalogue saison 1*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_third_slice.default.primary.catalogue_saison_1[].valeur_traitee
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  valeur_traitee: prismic.RichTextField;

  /**
   * Titre de conte field in *CatalogueThirdSlice → Default → Primary → Catalogue saison 1*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_third_slice.default.primary.catalogue_saison_1[].titre_de_conte
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_de_conte: prismic.KeyTextField;
}

/**
 * Item in *CatalogueThirdSlice → Default → Primary → Catalogue saison 2*
 */
export interface CatalogueThirdSliceSliceDefaultPrimaryCatalogueSaison2Item {
  /**
   * Image catalogue field in *CatalogueThirdSlice → Default → Primary → Catalogue saison 2*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_third_slice.default.primary.catalogue_saison_2[].image_cata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_cata: prismic.ImageField<never>;

  /**
   * Valeur traîtée field in *CatalogueThirdSlice → Default → Primary → Catalogue saison 2*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_third_slice.default.primary.catalogue_saison_2[].valeur_traitee
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  valeur_traitee: prismic.RichTextField;

  /**
   * Titre de conte field in *CatalogueThirdSlice → Default → Primary → Catalogue saison 2*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_third_slice.default.primary.catalogue_saison_2[].titre_de_conte
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_de_conte: prismic.KeyTextField;
}

/**
 * Item in *CatalogueThirdSlice → Default → Primary → Catalogue saison 3*
 */
export interface CatalogueThirdSliceSliceDefaultPrimaryCatalogueSaison3Item {
  /**
   * Image catalogue field in *CatalogueThirdSlice → Default → Primary → Catalogue saison 3*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_third_slice.default.primary.catalogue_saison_3[].image_catalogue
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_catalogue: prismic.ImageField<never>;

  /**
   * Valeur traîtée field in *CatalogueThirdSlice → Default → Primary → Catalogue saison 3*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_third_slice.default.primary.catalogue_saison_3[].valeur_traitee
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  valeur_traitee: prismic.RichTextField;

  /**
   * Titre de conte field in *CatalogueThirdSlice → Default → Primary → Catalogue saison 3*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_third_slice.default.primary.catalogue_saison_3[].titre_de_conte
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_de_conte: prismic.KeyTextField;
}

/**
 * Primary content in *CatalogueThirdSlice → Default → Primary*
 */
export interface CatalogueThirdSliceSliceDefaultPrimary {
  /**
   * Titre saison 1 field in *CatalogueThirdSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_third_slice.default.primary.titre_saison_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre_saison_1: prismic.RichTextField;

  /**
   * Catalogue saison 1 field in *CatalogueThirdSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_third_slice.default.primary.catalogue_saison_1[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  catalogue_saison_1: prismic.GroupField<
    Simplify<CatalogueThirdSliceSliceDefaultPrimaryCatalogueSaison1Item>
  >;

  /**
   * Titre saison 2 field in *CatalogueThirdSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_third_slice.default.primary.titre_saison_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre_saison_2: prismic.RichTextField;

  /**
   * Catalogue saison 2 field in *CatalogueThirdSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_third_slice.default.primary.catalogue_saison_2[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  catalogue_saison_2: prismic.GroupField<
    Simplify<CatalogueThirdSliceSliceDefaultPrimaryCatalogueSaison2Item>
  >;

  /**
   * Titre saison 3 field in *CatalogueThirdSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_third_slice.default.primary.titre_saison_3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre_saison_3: prismic.RichTextField;

  /**
   * Catalogue saison 3 field in *CatalogueThirdSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: catalogue_third_slice.default.primary.catalogue_saison_3[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  catalogue_saison_3: prismic.GroupField<
    Simplify<CatalogueThirdSliceSliceDefaultPrimaryCatalogueSaison3Item>
  >;
}

/**
 * Default variation for CatalogueThirdSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CatalogueThirdSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CatalogueThirdSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CatalogueThirdSlice*
 */
type CatalogueThirdSliceSliceVariation = CatalogueThirdSliceSliceDefault;

/**
 * CatalogueThirdSlice Shared Slice
 *
 * - **API ID**: `catalogue_third_slice`
 * - **Description**: CatalogueThirdSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CatalogueThirdSliceSlice = prismic.SharedSlice<
  "catalogue_third_slice",
  CatalogueThirdSliceSliceVariation
>;

/**
 * Item in *CatchPhraseSection → Default → Primary → Button à propos*
 */
export interface CatchPhraseSectionSliceDefaultPrimaryButtonAProposItem {
  /**
   * Label  field in *CatchPhraseSection → Default → Primary → Button à propos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.button_a_propos[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Lien field in *CatchPhraseSection → Default → Primary → Button à propos*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.button_a_propos[].lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien: prismic.LinkField;
}

/**
 * Item in *CatchPhraseSection → Default → Primary → Section photo personnes ayant testé*
 */
export interface CatchPhraseSectionSliceDefaultPrimarySectionPhotoPersonnesAyantTesteItem {
  /**
   * Photo field in *CatchPhraseSection → Default → Primary → Section photo personnes ayant testé*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.section_photo_personnes_ayant_teste[].photo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo: prismic.ImageField<never>;

  /**
   * numbre de personnes ayant aimées field in *CatchPhraseSection → Default → Primary → Section photo personnes ayant testé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.section_photo_personnes_ayant_teste[].numbre_de_personnes_ayant_aimees
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  numbre_de_personnes_ayant_aimees: prismic.KeyTextField;
}

/**
 * Primary content in *CatchPhraseSection → Default → Primary*
 */
export interface CatchPhraseSectionSliceDefaultPrimary {
  /**
   * Titre field in *CatchPhraseSection → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre: prismic.TitleField;

  /**
   * Sous-titre field in *CatchPhraseSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.sous_titre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sous_titre: prismic.RichTextField;

  /**
   * photo mobile field in *CatchPhraseSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.photo_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo_mobile: prismic.ImageField<never>;

  /**
   * Button à propos field in *CatchPhraseSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.button_a_propos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  button_a_propos: prismic.GroupField<
    Simplify<CatchPhraseSectionSliceDefaultPrimaryButtonAProposItem>
  >;

  /**
   * Section photo personnes ayant testé field in *CatchPhraseSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.section_photo_personnes_ayant_teste[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  section_photo_personnes_ayant_teste: prismic.GroupField<
    Simplify<CatchPhraseSectionSliceDefaultPrimarySectionPhotoPersonnesAyantTesteItem>
  >;

  /**
   * Phrase des personnes qui ont testé field in *CatchPhraseSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catch_phrase_section.default.primary.phrase_des_personnes_qui_ont_testes
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phrase_des_personnes_qui_ont_testes: prismic.RichTextField;
}

/**
 * Default variation for CatchPhraseSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CatchPhraseSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CatchPhraseSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CatchPhraseSection*
 */
type CatchPhraseSectionSliceVariation = CatchPhraseSectionSliceDefault;

/**
 * CatchPhraseSection Shared Slice
 *
 * - **API ID**: `catch_phrase_section`
 * - **Description**: CatchPhraseSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CatchPhraseSectionSlice = prismic.SharedSlice<
  "catch_phrase_section",
  CatchPhraseSectionSliceVariation
>;

/**
 * Primary content in *Developpement → Default → Primary*
 */
export interface DeveloppementSliceDefaultPrimary {
  /**
   * Étape field in *Developpement → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: developpement.default.primary.etape
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  etape: prismic.RichTextField;

  /**
   * Sous titre field in *Developpement → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: developpement.default.primary.sous_titre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sous_titre: prismic.TitleField;

  /**
   * Description field in *Developpement → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: developpement.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Valeur field in *Developpement → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: developpement.default.primary.valeur
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  valeur: prismic.RichTextField;

  /**
   * Titre de conte field in *Developpement → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: developpement.default.primary.titre_de_conte
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_de_conte: prismic.KeyTextField;

  /**
   * Image conte field in *Developpement → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: developpement.default.primary.image_conte
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_conte: prismic.ImageField<never>;

  /**
   * Icon audio play field in *Developpement → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: icon_play_circle
   * - **API ID Path**: developpement.default.primary.icon_audio_play
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon_audio_play: prismic.SelectField<
    "icon_play_circle" | "icon_play_square",
    "filled"
  >;

  /**
   * Icon audio pause field in *Developpement → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: icon_pause_circle
   * - **API ID Path**: developpement.default.primary.icon_audio_pause
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon_audio_pause: prismic.SelectField<
    "icon_pause_circle" | "icon_pause_square",
    "filled"
  >;

  /**
   * Audio coaching field in *Developpement → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: developpement.default.primary.audio_coaching
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  audio_coaching: prismic.LinkToMediaField;

  /**
   * Sous titre vidéo field in *Developpement → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: developpement.default.primary.sous_titre_video
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sous_titre_video: prismic.TitleField;

  /**
   * Catch phrase video leader field in *Developpement → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: developpement.default.primary.catch_phrase_video_leader
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  catch_phrase_video_leader: prismic.KeyTextField;

  /**
   * Video du leader field in *Developpement → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: developpement.default.primary.video_du_leader
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video_du_leader: prismic.EmbedField;

  /**
   * Video des leaders field in *Developpement → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: developpement.default.primary.video_des_leaders
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video_des_leaders: prismic.EmbedField;
}

/**
 * Default variation for Developpement Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DeveloppementSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DeveloppementSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Developpement*
 */
type DeveloppementSliceVariation = DeveloppementSliceDefault;

/**
 * Developpement Shared Slice
 *
 * - **API ID**: `developpement`
 * - **Description**: Developpement
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DeveloppementSlice = prismic.SharedSlice<
  "developpement",
  DeveloppementSliceVariation
>;

/**
 * Item in *EveilIndividuel → Default → Primary → Image et description*
 */
export interface EveilIndividuelSliceDefaultPrimaryImageEtDescriptionItem {
  /**
   * Image slider field in *EveilIndividuel → Default → Primary → Image et description*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: eveil_individuel.default.primary.image_et_description[].image_slider
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_slider: prismic.ImageField<never>;
}

/**
 * Item in *EveilIndividuel → Default → Primary → Button découvrire notre catalogue*
 */
export interface EveilIndividuelSliceDefaultPrimaryButtonCatalogueItem {
  /**
   * lien vers la page catalogue field in *EveilIndividuel → Default → Primary → Button découvrire notre catalogue*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: eveil_individuel.default.primary.button_catalogue[].lien_vers_la_page_catalogue
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien_vers_la_page_catalogue: prismic.LinkField;

  /**
   * Placeholder button field in *EveilIndividuel → Default → Primary → Button découvrire notre catalogue*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: eveil_individuel.default.primary.button_catalogue[].placeholder_button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  placeholder_button: prismic.KeyTextField;
}

/**
 * Primary content in *EveilIndividuel → Default → Primary*
 */
export interface EveilIndividuelSliceDefaultPrimary {
  /**
   * Titre field in *EveilIndividuel → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: eveil_individuel.default.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre: prismic.TitleField;

  /**
   * Sous titre field in *EveilIndividuel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: eveil_individuel.default.primary.sous_titre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sous_titre: prismic.RichTextField;

  /**
   * Image et description field in *EveilIndividuel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: eveil_individuel.default.primary.image_et_description[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  image_et_description: prismic.GroupField<
    Simplify<EveilIndividuelSliceDefaultPrimaryImageEtDescriptionItem>
  >;

  /**
   * Button découvrire notre catalogue field in *EveilIndividuel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: eveil_individuel.default.primary.button_catalogue[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  button_catalogue: prismic.GroupField<
    Simplify<EveilIndividuelSliceDefaultPrimaryButtonCatalogueItem>
  >;
}

/**
 * Default variation for EveilIndividuel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EveilIndividuelSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EveilIndividuelSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EveilIndividuel*
 */
type EveilIndividuelSliceVariation = EveilIndividuelSliceDefault;

/**
 * EveilIndividuel Shared Slice
 *
 * - **API ID**: `eveil_individuel`
 * - **Description**: EveilIndividuel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EveilIndividuelSlice = prismic.SharedSlice<
  "eveil_individuel",
  EveilIndividuelSliceVariation
>;

/**
 * Item in *FirstSliceFormation → Default → Primary → Button nous contacter*
 */
export interface FirstSliceFormationSliceDefaultPrimaryButtonNousContacterItem {
  /**
   * Text button field in *FirstSliceFormation → Default → Primary → Button nous contacter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_slice_formation.default.primary.button_nous_contacter[].text_button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_button: prismic.KeyTextField;

  /**
   * Lien vers la page contacter field in *FirstSliceFormation → Default → Primary → Button nous contacter*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: first_slice_formation.default.primary.button_nous_contacter[].lien_vers_la_page_contacter
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien_vers_la_page_contacter: prismic.LinkField;
}

/**
 * Item in *FirstSliceFormation → Default → Primary → Description Outils Timeo*
 */
export interface FirstSliceFormationSliceDefaultPrimaryDescriptionOutilsTimeoItem {
  /**
   * Titre field in *FirstSliceFormation → Default → Primary → Description Outils Timeo*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_slice_formation.default.primary.description_outils_timeo[].titre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre: prismic.RichTextField;

  /**
   * Description field in *FirstSliceFormation → Default → Primary → Description Outils Timeo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_slice_formation.default.primary.description_outils_timeo[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *FirstSliceFormation → Default → Primary*
 */
export interface FirstSliceFormationSliceDefaultPrimary {
  /**
   * Image de fond de page field in *FirstSliceFormation → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: first_slice_formation.default.primary.image_de_fond
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_de_fond: prismic.ImageField<never>;

  /**
   * Titre field in *FirstSliceFormation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_slice_formation.default.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre: prismic.RichTextField;

  /**
   * Sous titre field in *FirstSliceFormation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_slice_formation.default.primary.sous_titre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sous_titre: prismic.RichTextField;

  /**
   * Button nous contacter field in *FirstSliceFormation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: first_slice_formation.default.primary.button_nous_contacter[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  button_nous_contacter: prismic.GroupField<
    Simplify<FirstSliceFormationSliceDefaultPrimaryButtonNousContacterItem>
  >;

  /**
   * Description Outils Timeo field in *FirstSliceFormation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: first_slice_formation.default.primary.description_outils_timeo[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  description_outils_timeo: prismic.GroupField<
    Simplify<FirstSliceFormationSliceDefaultPrimaryDescriptionOutilsTimeoItem>
  >;
}

/**
 * Default variation for FirstSliceFormation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FirstSliceFormationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FirstSliceFormationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FirstSliceFormation*
 */
type FirstSliceFormationSliceVariation = FirstSliceFormationSliceDefault;

/**
 * FirstSliceFormation Shared Slice
 *
 * - **API ID**: `first_slice_formation`
 * - **Description**: FirstSliceFormation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FirstSliceFormationSlice = prismic.SharedSlice<
  "first_slice_formation",
  FirstSliceFormationSliceVariation
>;

/**
 * Item in *PageAPropos → Default → Primary → Button nous contacter*
 */
export interface PageAProposSliceDefaultPrimaryButtonNousContacterItem {
  /**
   * Placeholder field in *PageAPropos → Default → Primary → Button nous contacter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_a_propos.default.primary.button_nous_contacter[].placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  placeholder: prismic.KeyTextField;

  /**
   * Lien vers la page contacter field in *PageAPropos → Default → Primary → Button nous contacter*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page_a_propos.default.primary.button_nous_contacter[].lien_vers_la_page_contacter
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien_vers_la_page_contacter: prismic.LinkField;
}

/**
 * Item in *PageAPropos → Default → Primary → Créatrice Timéo*
 */
export interface PageAProposSliceDefaultPrimaryCreatriceTimeoItem {
  /**
   * Image créatrice field in *PageAPropos → Default → Primary → Créatrice Timéo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_a_propos.default.primary.creatrice_timeo[].image_creatrice
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_creatrice: prismic.ImageField<never>;

  /**
   * Nom field in *PageAPropos → Default → Primary → Créatrice Timéo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_a_propos.default.primary.creatrice_timeo[].nom
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nom: prismic.KeyTextField;

  /**
   * Titre field in *PageAPropos → Default → Primary → Créatrice Timéo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_a_propos.default.primary.creatrice_timeo[].titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Nom du lien vers le site field in *PageAPropos → Default → Primary → Créatrice Timéo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_a_propos.default.primary.creatrice_timeo[].nom_du_lien_vers_le_site
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nom_du_lien_vers_le_site: prismic.KeyTextField;

  /**
   * Site field in *PageAPropos → Default → Primary → Créatrice Timéo*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page_a_propos.default.primary.creatrice_timeo[].site
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  site: prismic.LinkField;

  /**
   * lien linkIdn field in *PageAPropos → Default → Primary → Créatrice Timéo*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page_a_propos.default.primary.creatrice_timeo[].lien_linkidn
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien_linkidn: prismic.LinkField;

  /**
   * Description field in *PageAPropos → Default → Primary → Créatrice Timéo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_a_propos.default.primary.creatrice_timeo[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *PageAPropos → Default → Primary*
 */
export interface PageAProposSliceDefaultPrimary {
  /**
   * Titre field in *PageAPropos → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_a_propos.default.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre: prismic.RichTextField;

  /**
   * Description Timéo field in *PageAPropos → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_a_propos.default.primary.description_timeo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_timeo: prismic.RichTextField;

  /**
   * Button nous contacter field in *PageAPropos → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: page_a_propos.default.primary.button_nous_contacter[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  button_nous_contacter: prismic.GroupField<
    Simplify<PageAProposSliceDefaultPrimaryButtonNousContacterItem>
  >;

  /**
   * Créatrice Timéo field in *PageAPropos → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: page_a_propos.default.primary.creatrice_timeo[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  creatrice_timeo: prismic.GroupField<
    Simplify<PageAProposSliceDefaultPrimaryCreatriceTimeoItem>
  >;
}

/**
 * Default variation for PageAPropos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageAProposSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PageAProposSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PageAPropos*
 */
type PageAProposSliceVariation = PageAProposSliceDefault;

/**
 * PageAPropos Shared Slice
 *
 * - **API ID**: `page_a_propos`
 * - **Description**: PageAPropos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageAProposSlice = prismic.SharedSlice<
  "page_a_propos",
  PageAProposSliceVariation
>;

/**
 * Primary content in *PageContact → Default → Primary*
 */
export interface PageContactSliceDefaultPrimary {
  /**
   * Titre page de contact field in *PageContact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.default.primary.titre_page_contact
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre_page_contact: prismic.RichTextField;

  /**
   * Label Pseudo field in *PageContact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.default.primary.label_pseudo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_pseudo: prismic.KeyTextField;

  /**
   * Pseudo utilisateur field in *PageContact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.default.primary.pseudo_utilisateur
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pseudo_utilisateur: prismic.KeyTextField;

  /**
   * Label Adresse Mail field in *PageContact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.default.primary.label_adresse_mail
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_adresse_mail: prismic.KeyTextField;

  /**
   * Adresse mail field in *PageContact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.default.primary.adresse_mail
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  adresse_mail: prismic.KeyTextField;

  /**
   * Label Message field in *PageContact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.default.primary.label_message
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_message: prismic.KeyTextField;

  /**
   * champ de message field in *PageContact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.default.primary.champ_de_message
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  champ_de_message: prismic.KeyTextField;

  /**
   * Image icon message field in *PageContact → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.default.primary.image_icon_message
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_icon_message: prismic.ImageField<never>;

  /**
   * button envoyer field in *PageContact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.default.primary.button_envoyer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_envoyer: prismic.KeyTextField;
}

/**
 * Default variation for PageContact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PageContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PageContact*
 */
type PageContactSliceVariation = PageContactSliceDefault;

/**
 * PageContact Shared Slice
 *
 * - **API ID**: `page_contact`
 * - **Description**: PageContact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageContactSlice = prismic.SharedSlice<
  "page_contact",
  PageContactSliceVariation
>;

/**
 * Primary content in *ParcoursTimeo → Default → Primary*
 */
export interface ParcoursTimeoSliceDefaultPrimary {
  /**
   * Titre field in *ParcoursTimeo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parcours_timeo.default.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre: prismic.RichTextField;

  /**
   * Étape éveil field in *ParcoursTimeo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parcours_timeo.default.primary.etape_eveil
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  etape_eveil: prismic.KeyTextField;

  /**
   * Étape developpement field in *ParcoursTimeo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parcours_timeo.default.primary.etape_developpement
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  etape_developpement: prismic.KeyTextField;

  /**
   * Étape transformation field in *ParcoursTimeo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parcours_timeo.default.primary.etape_transformation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  etape_transformation: prismic.KeyTextField;
}

/**
 * Primary content in *ParcoursTimeo → Items*
 */
export interface ParcoursTimeoSliceDefaultItem {
  /**
   * Icon field in *ParcoursTimeo → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: parcours_timeo.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<
    "eveil" | "developpement" | "transformation" | "Timeo"
  >;

  /**
   * Etape field in *ParcoursTimeo → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parcours_timeo.items[].etape
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  etape: prismic.KeyTextField;
}

/**
 * Default variation for ParcoursTimeo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParcoursTimeoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ParcoursTimeoSliceDefaultPrimary>,
  Simplify<ParcoursTimeoSliceDefaultItem>
>;

/**
 * Slice variation for *ParcoursTimeo*
 */
type ParcoursTimeoSliceVariation = ParcoursTimeoSliceDefault;

/**
 * ParcoursTimeo Shared Slice
 *
 * - **API ID**: `parcours_timeo`
 * - **Description**: ParcoursTimeo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParcoursTimeoSlice = prismic.SharedSlice<
  "parcours_timeo",
  ParcoursTimeoSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *SecondSliceFormation → Default → Primary → Section example de catalogues*
 */
export interface SecondSliceFormationSliceDefaultPrimarySectionExampleDeCataloguesItem {
  /**
   * Saison field in *SecondSliceFormation → Default → Primary → Section example de catalogues*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_slice_formation.default.primary.section_example_de_catalogues[].saison
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  saison: prismic.KeyTextField;

  /**
   * Catalogue field in *SecondSliceFormation → Default → Primary → Section example de catalogues*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: second_slice_formation.default.primary.section_example_de_catalogues[].catalogue
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  catalogue: prismic.ImageField<never>;

  /**
   * Titre catalogue field in *SecondSliceFormation → Default → Primary → Section example de catalogues*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_slice_formation.default.primary.section_example_de_catalogues[].titre_catalogue
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre_catalogue: prismic.RichTextField;

  /**
   * Sous titre catalogue field in *SecondSliceFormation → Default → Primary → Section example de catalogues*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_slice_formation.default.primary.section_example_de_catalogues[].sous_titre_catalogue
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sous_titre_catalogue: prismic.KeyTextField;

  /**
   * Text button field in *SecondSliceFormation → Default → Primary → Section example de catalogues*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_slice_formation.default.primary.section_example_de_catalogues[].text_button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_button: prismic.KeyTextField;

  /**
   * lien vers la page catalogue field in *SecondSliceFormation → Default → Primary → Section example de catalogues*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: second_slice_formation.default.primary.section_example_de_catalogues[].lien_vers_la_page_catalogue
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien_vers_la_page_catalogue: prismic.LinkField;
}

/**
 * Primary content in *SecondSliceFormation → Default → Primary*
 */
export interface SecondSliceFormationSliceDefaultPrimary {
  /**
   * Titre field in *SecondSliceFormation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_slice_formation.default.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre: prismic.RichTextField;

  /**
   * Sous titre field in *SecondSliceFormation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_slice_formation.default.primary.sous_titre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sous_titre: prismic.RichTextField;

  /**
   * Section example de catalogues field in *SecondSliceFormation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: second_slice_formation.default.primary.section_example_de_catalogues[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  section_example_de_catalogues: prismic.GroupField<
    Simplify<SecondSliceFormationSliceDefaultPrimarySectionExampleDeCataloguesItem>
  >;
}

/**
 * Default variation for SecondSliceFormation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecondSliceFormationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SecondSliceFormationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SecondSliceFormation*
 */
type SecondSliceFormationSliceVariation = SecondSliceFormationSliceDefault;

/**
 * SecondSliceFormation Shared Slice
 *
 * - **API ID**: `second_slice_formation`
 * - **Description**: SecondSliceFormation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecondSliceFormationSlice = prismic.SharedSlice<
  "second_slice_formation",
  SecondSliceFormationSliceVariation
>;

/**
 * Item in *Transformation → Default → Primary → Button*
 */
export interface TransformationSliceDefaultPrimaryButtonTransformationItem {
  /**
   * Lien vers la page field in *Transformation → Default → Primary → Button*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: transformation.default.primary.button_transformation[].lien_vers_la_page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien_vers_la_page: prismic.LinkField;

  /**
   * Placeholder button field in *Transformation → Default → Primary → Button*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: transformation.default.primary.button_transformation[].placeholder_button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  placeholder_button: prismic.KeyTextField;
}

/**
 * Item in *Transformation → Default → Primary → Button nous contacter*
 */
export interface TransformationSliceDefaultPrimaryButtonNousContacterItem {
  /**
   * Placeholder field in *Transformation → Default → Primary → Button nous contacter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: transformation.default.primary.button_nous_contacter[].placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  placeholder: prismic.KeyTextField;

  /**
   * Lien vers la page field in *Transformation → Default → Primary → Button nous contacter*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: transformation.default.primary.button_nous_contacter[].lien_vers_la_page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien_vers_la_page: prismic.LinkField;
}

/**
 * Primary content in *Transformation → Default → Primary*
 */
export interface TransformationSliceDefaultPrimary {
  /**
   * Étape field in *Transformation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: transformation.default.primary.etape
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  etape: prismic.RichTextField;

  /**
   * Description field in *Transformation → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: transformation.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Button field in *Transformation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: transformation.default.primary.button_transformation[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  button_transformation: prismic.GroupField<
    Simplify<TransformationSliceDefaultPrimaryButtonTransformationItem>
  >;

  /**
   * Text témoignage DeCathlon  field in *Transformation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: transformation.default.primary.text_temoignage_decathlon
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_temoignage_decathlon: prismic.RichTextField;

  /**
   * Vidéo explicative field in *Transformation → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: transformation.default.primary.video_explicative
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video_explicative: prismic.EmbedField;

  /**
   * Button nous contacter field in *Transformation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: transformation.default.primary.button_nous_contacter[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  button_nous_contacter: prismic.GroupField<
    Simplify<TransformationSliceDefaultPrimaryButtonNousContacterItem>
  >;
}

/**
 * Default variation for Transformation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TransformationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TransformationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Transformation*
 */
type TransformationSliceVariation = TransformationSliceDefault;

/**
 * Transformation Shared Slice
 *
 * - **API ID**: `transformation`
 * - **Description**: Transformation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TransformationSlice = prismic.SharedSlice<
  "transformation",
  TransformationSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataFooterItem,
      FooterDocumentDataPolitiquesDeConfidentialiteItem,
      MenuDocument,
      MenuDocumentData,
      MenuDocumentDataMenuDeNavigationItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CatalogueFirstSliceSlice,
      CatalogueFirstSliceSliceDefaultPrimaryLesOffresTimeoItem,
      CatalogueFirstSliceSliceDefaultPrimaryButtonNousContacterItem,
      CatalogueFirstSliceSliceDefaultPrimary,
      CatalogueFirstSliceSliceVariation,
      CatalogueFirstSliceSliceDefault,
      CatalogueSecondSliceSlice,
      CatalogueSecondSliceSliceDefaultPrimaryDetailDeContenusDeCoffretItem,
      CatalogueSecondSliceSliceDefaultPrimaryButtonDemanderUnDevisItem,
      CatalogueSecondSliceSliceDefaultPrimary,
      CatalogueSecondSliceSliceVariation,
      CatalogueSecondSliceSliceDefault,
      CatalogueThirdSliceSlice,
      CatalogueThirdSliceSliceDefaultPrimaryCatalogueSaison1Item,
      CatalogueThirdSliceSliceDefaultPrimaryCatalogueSaison2Item,
      CatalogueThirdSliceSliceDefaultPrimaryCatalogueSaison3Item,
      CatalogueThirdSliceSliceDefaultPrimary,
      CatalogueThirdSliceSliceVariation,
      CatalogueThirdSliceSliceDefault,
      CatchPhraseSectionSlice,
      CatchPhraseSectionSliceDefaultPrimaryButtonAProposItem,
      CatchPhraseSectionSliceDefaultPrimarySectionPhotoPersonnesAyantTesteItem,
      CatchPhraseSectionSliceDefaultPrimary,
      CatchPhraseSectionSliceVariation,
      CatchPhraseSectionSliceDefault,
      DeveloppementSlice,
      DeveloppementSliceDefaultPrimary,
      DeveloppementSliceVariation,
      DeveloppementSliceDefault,
      EveilIndividuelSlice,
      EveilIndividuelSliceDefaultPrimaryImageEtDescriptionItem,
      EveilIndividuelSliceDefaultPrimaryButtonCatalogueItem,
      EveilIndividuelSliceDefaultPrimary,
      EveilIndividuelSliceVariation,
      EveilIndividuelSliceDefault,
      FirstSliceFormationSlice,
      FirstSliceFormationSliceDefaultPrimaryButtonNousContacterItem,
      FirstSliceFormationSliceDefaultPrimaryDescriptionOutilsTimeoItem,
      FirstSliceFormationSliceDefaultPrimary,
      FirstSliceFormationSliceVariation,
      FirstSliceFormationSliceDefault,
      PageAProposSlice,
      PageAProposSliceDefaultPrimaryButtonNousContacterItem,
      PageAProposSliceDefaultPrimaryCreatriceTimeoItem,
      PageAProposSliceDefaultPrimary,
      PageAProposSliceVariation,
      PageAProposSliceDefault,
      PageContactSlice,
      PageContactSliceDefaultPrimary,
      PageContactSliceVariation,
      PageContactSliceDefault,
      ParcoursTimeoSlice,
      ParcoursTimeoSliceDefaultPrimary,
      ParcoursTimeoSliceDefaultItem,
      ParcoursTimeoSliceVariation,
      ParcoursTimeoSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SecondSliceFormationSlice,
      SecondSliceFormationSliceDefaultPrimarySectionExampleDeCataloguesItem,
      SecondSliceFormationSliceDefaultPrimary,
      SecondSliceFormationSliceVariation,
      SecondSliceFormationSliceDefault,
      TransformationSlice,
      TransformationSliceDefaultPrimaryButtonTransformationItem,
      TransformationSliceDefaultPrimaryButtonNousContacterItem,
      TransformationSliceDefaultPrimary,
      TransformationSliceVariation,
      TransformationSliceDefault,
    };
  }
}
