import "./globals.css"
import { PrismicPreview } from "@prismicio/next";
import { repositoryName } from "@/prismicio";
import Header from "@/components/nav/Header";
import { Footer } from "@/components/Footer/Footer";
import { Content } from "@prismicio/client";
import { Raleway, Cormorant, Proza_Libre } from 'next/font/google';

const raleway = Raleway({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
  variable: '--font-raleway',
});
const  cormorant = Cormorant({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
  variable: '--font-cormorant',
});
const  proza_libre = Proza_Libre ({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
  variable: '--font-proza_libre',
});

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  bgColor = "#e2e8f0",
}: Readonly<{
  children: React.ReactNode;
  bgColor: string;
  footer: Content.FooterDocument
}>) {
  return (
    <html lang="fr" className={`${raleway} ${cormorant} ${proza_libre}`}>
      <body>
        <Header />
        <main>
          {children}
        </main>
        <Footer bgColor={bgColor} />
      </body>
      <PrismicPreview repositoryName={repositoryName} />
    </html>
  );
}
