import "./globals.css"
import { PrismicPreview } from "@prismicio/next";
import { repositoryName } from "@/prismicio";
import Header from "@/components/nav/Header";
import { Footer } from "@/components/Footer/Footer";
import { Content } from "@prismicio/client";
import { Arima, Amaranth } from 'next/font/google';

const arima = Arima({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-arima',
});

const amaranth = Amaranth({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
  variable: '--font-amaranth',
});

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  bgColor = "#e2e8f0",
}: Readonly<{
  children: React.ReactNode;
  bgColor: string;
  footer: Content.FooterDocument
}>) {
  return (
    <html lang="fr" className={`${arima.variable} ${amaranth.variable}`}>
      <body>
        <Header />
        <main>
          {children}
        </main>
        <Footer bgColor={bgColor} />
      </body>
      <PrismicPreview repositoryName={repositoryName} />
    </html>
  );
}
