import "./globals.css"
import { PrismicPreview } from "@prismicio/next";
import { repositoryName } from "@/prismicio";
import Header from "@/components/nav/Header";
import { Footer } from "@/components/Footer/Footer";
import { Content } from "@prismicio/client";
import { Raleway, Cormorant, Proza_Libre } from 'next/font/google';
import { Analytics } from "@vercel/analytics/react"

const raleway = Raleway({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
  variable: '--font-raleway',
});
const  cormorant = Cormorant({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
  variable: '--font-cormorant',
});
const  proza_libre = Proza_Libre ({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
  variable: '--font-proza_libre',
});

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${raleway.variable} ${cormorant.variable} ${proza_libre.variable}`}>
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
        <Analytics />
      </body>
      <PrismicPreview repositoryName={repositoryName} />
    </html>
  );
}
