// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  catch_phrase_section: dynamic(() => import("./CatchPhraseSection")),
  developpement: dynamic(() => import("./Developpement")),
  eveil_individuel: dynamic(() => import("./EveilIndividuel")),
  page_a_propos: dynamic(() => import("./PageAPropos")),
  page_contact: dynamic(() => import("./PageContact")),
  parcours_timeo: dynamic(() => import("./ParcoursTimeo")),
  rich_text: dynamic(() => import("./RichText")),
  transformation: dynamic(() => import("./Transformation")),
};
